services:
  - type: worker
    name: prop-firm-signal-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    autoDeploy: true
    envVars:
      - key: TWELVEDATA_API_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
